# Generated by Django 5.2 on 2025-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('expiry_date', models.DateField()),
                ('category', models.CharField(choices=[('Produce', 'Produce'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Bakery', 'Bakery')], max_length=50)),
                ('cost_per_kg', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('Produce', 'Produce'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Bakery', 'Bakery')], max_length=50)),
                ('cost', models.FloatField()),
            ],
        ),
    ]
