# Generated by Django 5.2 on 2025-04-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='cost_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wastedata',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wastedata',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
